### ISSUE TITLE
View problem

### ISSUE THREAD

**Issue by orinmurphy** [jamztang/CSStickyHeaderFlowLayout#105]
Im using the "AlwaysOnTopHeader" layout.
I've added a tab bar in the sectionHeader where I can populate the CSCells with different data when I select different tabs.

The issue im having is when I scroll up to show 15 or so CSCells, and I tab to an array that will only return 8 cells, the top of the screen is dragged down because the table size has changed. I've attached a screen of the issue. Any ideas?

![img_1538](https://cloud.githubusercontent.com/assets/3251360/10175987/09899a4c-66c0-11e5-9176-954e06782486.PNG)

**Comment by jamztang** [comment]
would setting contentOffset.y to 0 manually help with that?

**Comment by orinmurphy** [comment]
reloading the layout works. thanks
