### ISSUE TITLE
segmented control on the section header to switch two collection views 

### ISSUE THREAD

**Issue by deter3** [jamztang/CSStickyHeaderFlowLayout#110]
I am trying to implement  a segmented control on the section header to switch two collections views ,  both collection view have same map view( no change when switch ) as ParallaxHeader and images as collection view cells , the segmented control section header will be sticky  header . Is that possible ? if yes , how can i do it with CSStickyHeaderFlowLayout in swift 2 , thanks a lot .

**Comment by deter3** [comment]
I have finally figured out how to do it . 

1. program segment control code in CollectiontoViewSectionHeader.swift ,send notification to collectionviewcontroller.swift 
2. collectionviewcontroller.swift  receive the notification and perform datasource switch .

**Comment by yoshiboarder** [comment]
Hi did you solved this problem? If so could you let me know?
