### ISSUE TITLE
Parallax with TableView Header

### ISSUE THREAD

**Issue by swalehap** [jamztang/CSStickyHeaderFlowLayout#124]
Can we implement the library for TableView?
I want parallax effect with sticky header view.

**Comment by Omarj** [comment]
Da same here :) can you please support tableView ?

**Comment by swalehap** [comment]
Yes the library is good but it should support tableView as well since tableView is commonly used.

**Comment by jamztang** [comment]
Sorry currently there's no plans for that.
The main intention for this library is to replace UITableView by providing a ready to use UICollectionViewLayout subclass.

There're other libraries provide support for UITableView parallax header tho
