### ISSUE TITLE
Header overlaps collectionView cells.

### ISSUE THREAD

**Issue by andrewjburnett** [jamztang/CSStickyHeaderFlowLayout#125]
When scrolling, the header overlaps the UICollectionView's cells.

**Comment by ppamorim** [comment]
+1 same here

**Comment by andrewjburnett** [comment]
@ppamorim I should have updated/closed this already. I suppose I had expected the "magic" of the header to just happen for me. Since I am developing most of my application programmatically, I made the mistake of ignoring the .xib provided in the example projects. It turns out it's very necessary to correctly set autoresizingMask, clipsToBounds, contentMode to all of the view involved in the header (self, contentView, and subviews, etc.). Additionally, real magic of CSStickyHeaderFlowLayout happens when you start playing around with the constraints of your views. 

Just for further clarification, here's how I set up my header's appearance related properties in its `initWithFrame:`

```
// self
self.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
self.contentMode = UIViewContentModeCenter;
self.clipsToBounds = YES;
// contentView
self.contentView.contentMode = UIViewContentModeCenter;
self.contentView.clipsToBounds = YES; 
````

Then, I added a subview called "contentContainerView" to my cell's contentView.

Here's how I set up the appearance related properties of the contentContainerView:

```
_contentContainerView.translatesAutoresizingMaskIntoConstraints = NO;
_contentContainerView.contentMode = UIViewContentModeScaleToFill;
_contentContainerView.clipsToBounds = YES;
```

I then add any further subviews to the contentContainer view and played around with their constraints to the desired behavior. You can also play around with the contentContainerView's height and top/bottom bounding constraints. You should do the same with any additional "content container" views you want to add in order to have particular view elements within your header move, or not move, in response to scrolling.

**Comment by talentedmobile** [comment]
Same here

**Comment by andrewjburnett** [comment]
@talentedmobile Did you try what I suggested above?

**Comment by ppamorim** [comment]
@andreamazz Fixed to me too. Thanks!
