### ISSUE TITLE
iOS 10 crash when scroll

### ISSUE THREAD

**Issue by monzy613** [jamztang/CSStickyHeaderFlowLayout#134]
this issue happend again https://github.com/jamztang/CSStickyHeaderFlowLayout/issues/18

**Comment by maleksiuk** [comment]
I don't use this software but there is similar custom functionality on a project I'm working on.  Turning off prefetching on the UICollectionView fixed it for me, so that might be an option for you @monzy613 if it doesn't get fixed properly in time.

**Comment by monzy613** [comment]
@maleksiuk thank u!! that really help, so what the hell is this preoperty, I've never heard before iOS 10, also the apple document seem saying nothing

**Comment by maleksiuk** [comment]
@monzy613 Yes that WWDC video and transcript is the same place I learned about it.  I don't know anything else about it.

**Comment by monzy613** [comment]
@maleksiuk in our project most devs still using xcode 7, so this bug will remain sometimes.. thus problem solved, I can close the

**Comment by monzy613** [comment]
@maleksiuk in our project most devs still using xcode 7, so this bug will remain sometimes..  Thanks really, this already took me long time!

**Comment by GabrielMSharp** [comment]
Temporary fix is to select UICollectionView in storyboard and in the Attributes Editor, disable "Prefetching Enabled". However this feature sounds very advantageous so I hope a fix can be found soon.

**Comment by EmanRezk** [comment]
@maleksiuk Thanks for you
