### ISSUE TITLE
Sticky header for only one section (not first section header)

### ISSUE THREAD

**Issue by laud** [jamztang/CSStickyHeaderFlowLayout#136]
Is there a simple way to only have one section header be sticky, and have all other section headers float with the content? 

Specifically, say I have three header sections in my collection view. I want the 1st and 3rd section header to float. However, I want the second header to stick.

**Comment by zachlucas** [comment]
I have the same issue, any advice?

**Comment by laud** [comment]
I ended up using the native iOS sticky header implementation. To make this work, I used multiple sections. The important detail to know is that section headers with no content do not stick whereas headers with content do stick.
