### ISSUE TITLE
Sticky Header programmatically

### ISSUE THREAD

**Issue by chancharles** [jamztang/CSStickyHeaderFlowLayout#16]
Thanks for creating such a easy to use library. I can successfully implement the "Always On Top" sample on my app using IB. However, when I try to do everything in code, I am a little bit stuck (which means that I am not fully understanding the mechanism). 

Anyway, can you please explain how the "Shuffle" button (in the Always On Top sample) get scrolled with the rest of the collection while the parallax header remains there?  The header and the shuffle button belong to the same XIB and Cell class. 

I created a GroupHeaderCell to represent the parallax header (see below). But when I scroll, the header remains there. I would want the tabBar to be scrolled up and be sticky at the top.

Any idea would help.

Thanks!

``` swift
  class GroupHeaderCell: UICollectionViewCell, UITabBarDelegate {

   var backgroundImage: UIImageView?

   init(frame: CGRect) {
    NSLog("GroupHeaderCell initWithFrame \(frame.origin.x) x \(frame.origin.y) @ (\(frame.width), \(frame.height))")
    super.init(frame: frame)

    let tabBar = UITabBar(frame: CGRectMake(0, 200, frame.width, 80))
    tabBar.delegate = self

    let tabBarItem = UITabBarItem(tabBarSystemItem: UITabBarSystemItem.Favorites, tag: 1)
    tabBar.items = [ tabBarItem ]

    self.backgroundImage = UIImageView(frame:CGRectMake(0, 0, frame.width, 200))
    self.contentView.addSubview(self.backgroundImage)
    self.contentView.addSubview(tabBar)
    self.backgroundColor = UIColor.redColor()
  }
```

**Comment by chrise86** [comment]
I'm not able to get this working, @chancharles how did you implement it? My header stays where it is and I can't figure out how to keep just the buttons stuck to the top...
