### ISSUE TITLE
Unexpected behaviour when inserting new cells. 

### ISSUE THREAD

**Issue by markst** [jamztang/CSStickyHeaderFlowLayout#30]
I have my `UICollectionView` backed by a `NSFetchedResultsController` to insert/update cells. 

My cells get inserted as the user scrolls. What seems to happen is the sticky headers scroll down & then return once the bounce deceleration animation is complete. 

I think a solution would be to only insert cells once animation deceleration is complete.

**Comment by jamztang** [comment]
0.2.8 has some updates on better handing animation, please feel free to reopen if still have issues.
