### ISSUE TITLE
Crash on iOS 8.1

### ISSUE THREAD

**Issue by Ouatelse** [jamztang/CSStickyHeaderFlowLayout#38]
Hi jamztang,

Your CSStickyHeaderFlowLayout is good but it crash on iOS 8.1

@implementation CSStickyHeaderFlowLayout
...
- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect
  {
  // The rect should compensate the header size
  CGRect adjustedRect = rect;
  adjustedRect.origin.y -= self.parallaxHeaderReferenceSize.height;

=>>    NSMutableArray *allItems = [[super layoutAttributesForElementsInRect:adjustedRect] mutableCopy]; // Crash is here

2014-11-03 10:54:21.844 AlloCine[313:44884] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

Can you check if you have this crash too please ?

Thanks for your help.

Ouatelse !

**Comment by jurajantas** [comment]
Hi, It does crash when iOS8 cell autosizing is enabled. (xcode 6.1, iOS8.1)
Just add this when setting up layout:
layout.estimatedItemSize = CGSizeMake(320, 80);

**Comment by netwire88** [comment]
I also get the same crash. I have this:

```
override func viewWillLayoutSubviews() {
            stickyLayout.estimatedItemSize = CGSize(width: desiredWidth, height: desiredHeight)
}
```

and the crash happens in
```
- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath {
    UICollectionViewLayoutAttributes *attributes = [super layoutAttributesForItemAtIndexPath:indexPath];  <-----
    CGRect frame = attributes.frame;
    frame.origin.y += self.parallaxHeaderReferenceSize.height;
    attributes.frame = frame;
    return attributes;
}
```
with this error: `EXC_ARITHMETIC code EXC_I386_DIV`

**Comment by jamztang** [comment]
right, estimatedItemSize is not supported right now, have been trying to make it work but no luck. However using estimatedItemSize has much more other issues even when using the vanilla collecitonViewLayout, I'm suggesting that we should probably wait iOS 9 and see if there're more improvement to it
