### ISSUE TITLE
Flow Layout debug warning

### ISSUE THREAD

**Issue by davepotts** [jamztang/CSStickyHeaderFlowLayout#40]
A BIG thank you for the fantastic flow layout solution.

One small issue I have is when the header has been stretched and is allowed to bounce back to its original height i get...

**the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.**

Its not so much a bug but more of a frustration as it spams the console for as many frames it takes for the collection view to come to rest. 

Any ideas on how to fix this?

**Comment by kamarshad** [comment]
Set self.automaticallyAdjustsScrollViewInsets = NO; in ViewController Class 
And Check @davepotts

**Comment by jamztang** [comment]
Thanks for the pointer @kamarshad !
