### ISSUE TITLE
EXC_BAD_ACCESS on [super collectionViewContentSize];

### ISSUE THREAD

**Issue by bezigon** [jamztang/CSStickyHeaderFlowLayout#43]
I have spotted this issue in iPad Mini with iOS 8.1.1 and I can repeat them.

I have a storyboard with navigation controller and two view controllers.
I use CSStickyHeaderFlowLayout in these two view controllers.

When I segued to second view controller from the main view controller, and at this moment I quickly tapped on the back button. Voila... EXC_BAD_ACCESS.

![screen shot 2014-12-11 at 6 03 41 pm](https://cloud.githubusercontent.com/assets/771853/5397092/20ee1262-8160-11e4-9964-3a4a8c2d604e.png)

By the way I used ``[self.collectionView reloadSections:[NSIndexSet indexSetWithIndex:...]];`` in sectioned collectionView.

Solution?

**Comment by jamztang** [comment]
Does that happen if you're using the default layout?

**Comment by marciomeschini** [comment]
Hi all,

I had the same issue. 
I added the following check in CSStickyHeaderFlowLayout:

```
- (CGSize)collectionViewContentSize {
    if (!self.collectionView.superview) { // If not part of view hierarchy then return zero size
        return CGSizeZero;
    }
    CGSize size = [super collectionViewContentSize]; // this causes the EXC_BAD_ACCESS  
    size.height += self.parallaxHeaderReferenceSize.height;
    return size;
}
```

I tested for a while and it seems that makes the fix. I'm happy to make a PR if you want me to do that.
Thanks for your nice library!

**Comment by jamztang** [comment]
PR would be absolutely appreciated! Just a question in what situation the CollectionView will lose it superview?

**Comment by marciomeschini** [comment]
I've been tested this with
* push a new vc and then straight after tap the back button 

Same context as @bezigon. I just stopped with debugger and did a quick check on the superview (nil). It would be nice to investigate it more and see the stack. It's a quite edge case for the user but better to not crash for now.

**Comment by jamztang** [comment]
Okay so the exact triggering point. I haven't got a chance to test it out myself that's why appreciate your double confirmation! Thanks @marciomeschini, will await your PR :)
