### ISSUE TITLE
Section Header can't receive touches

### ISSUE THREAD

**Issue by jpark822** [jamztang/CSStickyHeaderFlowLayout#49]
I have an outlet to a UISwitch in a UICollectionViewCell that is returned as a section header inside of:

func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView

I am unable to touch the switch, or any interactive controls, inside of the section header. However, controls inside the non-header cells are fine.

**Comment by jamztang** [comment]
Hi @jpark822 So in our example we were using CSCell for section headers, which is a subclass of UICollectionViewCell. We should create a proper subclass of UICollectionReusableView for section headers in order to have the touches receives properly. I've updated the example, please have a look!

**Comment by jpark822** [comment]
works great! thanks!

**Comment by jamztang** [comment]
No problem!
