### ISSUE TITLE
ContentOffset on bottom causes flickering to occur when scrolling down

### ISSUE THREAD

**Issue by joslinm** [jamztang/CSStickyHeaderFlowLayout#50]
If you set the contentOffset's bottom of the collectionView to 200+, you should see it. When you scroll down(as in, swiping up with your thumb to get to the bottom of the feed), the parallax header at top disappears for a second then reappears. This is obvious when you have a lot of velocity going into the bounce. 

Where does it go during this?

I've been able to capture the moments in which it disappears (I set a breakpoint when the difference between pastY and currentY are > 40), and have played with quite a few variables, but can't get it. Can you please have a look when you get the chance? If it helps, I have:

- Parallax header (min: 80px)
- Sticky header (100px)
- Rows of 120px

The parallax header disappears momentarily and I see the rows and header -- sometimes even the back of the collectionview. There's times when you can stop directly on it just manually scrolling. If the update finishes and Z isn't 2000 (I think), then it's not to be found.

**Comment by joslinm** [comment]
Tried re-creating this, and found the culprit. I was invalidating the layout after laying out the subviews therefore causing a flicker. 

```swift
// wrong order
collectionView!.collectionViewLayout.invalidateLayout()
collectionView!.layoutSubviews()
// correct order
collectionView!.collectionViewLayout.invalidateLayout()
collectionView!.layoutSubviews()

```

**Comment by jamztang** [comment]
👍

**Comment by sashagood** [comment]
I have the same problem.
