### ISSUE TITLE
How to collapse CSAlwaysOnTopHeader

### ISSUE THREAD

**Issue by elibud** [jamztang/CSStickyHeaderFlowLayout#51]
Congrats on a great library. I'm using it to do something very similar to the spotify example, but I want the header to be initially collapsed (only the spotify button displayed, hidden picture, etc), how can I achieve this? I've tried setting the frame programatically upon initialisation but this causes some odd flickering on the first expansion, probably due to the layout constraints being incorrect. Thx in advance.

**Comment by jamztang** [comment]
You should probably set the contentOffset

**Comment by elibud** [comment]
The contentOffset of the UICollectionView? I just want to affect the header.

**Comment by elibud** [comment]
Yep, contentOffset on the collection view, worked perfectly. Thanks a lot.
