### ISSUE TITLE
Autolayout for header?

### ISSUE THREAD

**Issue by gratif** [jamztang/CSStickyHeaderFlowLayout#52]
Anyone has hints on how to implement autolayout for the header size so it'll play nice for different orientations nicely?

**Comment by jamztang** [comment]
The easiest way is the conditionally set the parallaxHeaderReferenceSize.

Say your header size for iPhone 5 is 320 * 100, you want to maintain the same proportion for iPhone 6 and 6+, then it should be something similar to this.

```objective-c
CGFloat width = self.view.frame.size.width;
layout.parallaxHeaderReferenceSize = CGSizeMake(width, width / 320 * 100)
```

This is not literally using AutoLayout, but you know UITableView and UICollectionView wasn't designed to use auto layout anyway, so this is probably the easiest solution.

As a bonus tips, if you're working with device orientation, you probably want to put that line into `-[UIViewController viewWillLayoutSubview]`

**Comment by Fortrackz** [comment]
Here is a working solution for iOS 8.
```ObjC
- (void) viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
	//[super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
	CSStickyHeaderFlowLayout *layout = (id)self.collectionViewLayout;
	if ([layout isKindOfClass:[CSStickyHeaderFlowLayout class]])
	{
		layout.parallaxHeaderReferenceSize = CGSizeMake(size.width, 116 );
		layout.parallaxHeaderMinimumReferenceSize = CGSizeMake(size.width,64);
	}
	[self.collectionViewLayout invalidateLayout];
	
}
```

**Comment by jamztang** [comment]
Thanks for pointer in iOS 8 @Fortrackz !
