### ISSUE TITLE
No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by loretoparisi** [jamztang/CSStickyHeaderFlowLayout#53]
macbookproloreto:CSStickyHeaderFlowLayout admin$ pod install
[!] No `Podfile' found in the project directory.

**Comment by loretoparisi** [comment]
Found:

macbookproloreto:iOS admin$ git clone https://github.com/jamztang/CSStickyHeaderFlowLayout.git
Cloning into 'CSStickyHeaderFlowLayout'...
remote: Counting objects: 497, done.
remote: Total 497 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (497/497), 862.68 KiB | 501.00 KiB/s, done.
Resolving deltas: 100% (289/289), done.
Checking connectivity... done.
macbookproloreto:iOS admin$ cd C
CSStickyHeaderFlowLayout/   CustomFileHandler-master/   CustomInputViewDemo-master/ 
macbookproloreto:iOS admin$ cd CSStickyHeaderFlowLayout/Project/
macbookproloreto:Project admin$ ls -l
total 16
drwxr-xr-x  29 admin  staff  986 10 Feb 12:13 CSStickyHeaderFlowLayoutDemo
drwxr-xr-x   4 admin  staff  136 10 Feb 12:13 CSStickyHeaderFlowLayoutDemo.xcodeproj
drwxr-xr-x   4 admin  staff  136 10 Feb 12:13 CSStickyHeaderFlowLayoutDemo.xcworkspace
drwxr-xr-x   5 admin  staff  170 10 Feb 12:13 CSStickyHeaderFlowLayoutDemoTests
-rw-r--r--   1 admin  staff  100 10 Feb 12:13 Podfile
-rw-r--r--   1 admin  staff  329 10 Feb 12:13 Podfile.lock
drwxr-xr-x  17 admin  staff  578 10 Feb 12:13 Pods

**Comment by loretoparisi** [comment]
drwxr-xr-x  17 admin  staff  578 10 Feb 12:15 Pods
macbookproloreto:Project admin$ pod install
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Fetching podspec for `CSStickyHeaderFlowLayout` from `../CSStickyHeaderFlowLayout.podspec`
[!] Unable to satisfy the following requirements:

- `CSStickyHeaderFlowLayout (from `../CSStickyHeaderFlowLayout.podspec`)` required by `Podfile`
- `CSStickyHeaderFlowLayout (= 0.2)` required by `Podfile.lock`

**Comment by loretoparisi** [comment]
Damn you need a 

```pod update``` since everything is installed yet not a ```pod install```:

```
macbookproloreto:Project admin$ pod update
Update all pods
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Fetching podspec for `CSStickyHeaderFlowLayout` from `../CSStickyHeaderFlowLayout.podspec`
Downloading dependencies
Installing CSStickyHeaderFlowLayout 0.2.3 (was 0.2)
Generating Pods project
Integrating client project
```

**Comment by kaksisa** [comment]
I had to call:
/pod init 
while within the same directory as my *.xcodeproj , then I was able to call /pod install without the missing pod file error.
