### ISSUE TITLE
Removing cells changes the frame of the header. 

### ISSUE THREAD

**Issue by afriedman94** [jamztang/CSStickyHeaderFlowLayout#55]
Recreating the Spotify parallax. 

I have this issue where upon removing a cell from my collection view, the header's y origin will be offset by the offset of the last cell's view on the screen. For example, my cell's height is 55. If I scroll all the way to the bottom, and the entire last cell is showing, then remove a cell, the header will drop down 55 points. like this. 
![screen shot 2015-02-21 at 5 56 17 pm](https://cloud.githubusercontent.com/assets/7318614/6317059/09902c0e-ba0e-11e4-8734-ac97fe3bf159.png)

(That black space above the image is the offset, same height as my cells.) 

If only like half of the last cell is showing, then the header will drop down only like 22.5. Understand? 
If the last cell is not showing at all then everything updates as it should. 

Also, once the header is screwed up, as soon as scrollViewDidScroll, the header returns exactly to where it should be and everything works as it should again. 

Any idea how I can fix this?

**Comment by afriedman94** [comment]
So this is the best I've got so far. Doesn't seem like the right direction but it kind of works. 

  CGPoint offset = self.collectionView.contentOffset;
    CGRect bounds = self.collectionView.bounds;
    CGSize size = self.collectionView.contentSize;
    UIEdgeInsets inset = self.collectionView.contentInset;
    float y = offset.y + bounds.size.height - inset.bottom;
    float h = size.height;
    float cellOffset = (y - h) + 55;
    NSLog(@"%f", cellOffset);
    CurrentArtistHeader *header = (CurrentArtistHeader *)[self.collectionView viewWithTag:50];
    if (cellOffset > 0) {
        header.frame = CGRectMake(header.frame.origin.x,
                                  header.frame.origin.y - cellOffset,
                                  header.frame.size.width,
                                  header.frame.size.height);
    }


This will keep the header exactly where it should be at ALMOST all times. Now the only problem is that if the user removes a cell then removes another cell without scrolling, the same problem as before will happen because the collection view does not have the updated bounds. Scrolling seems to update the bounds, how do I programmatically update bounds upon removing a cell?

**Comment by afriedman94** [comment]
Okay so this weeds out all of the other bugs from my last post... 

    -(void)headerFrameForCellOffset
    {
     float stickyH = self.stickyHeaderFlowLayout.parallaxHeaderReferenceSize.height;
      float scrollBoundY = self.stickyHeaderFlowLayout.parallaxHeaderReferenceSize.height - self.stickyHeaderFlowLayout.parallaxHeaderMinimumReferenceSize.height;
    CGPoint offset = self.collectionView.contentOffset;
    CGRect bounds = self.collectionView.bounds;
    CGSize size = self.collectionView.contentSize;
    UIEdgeInsets inset = self.collectionView.contentInset;
    float y = offset.y + bounds.size.height - inset.bottom;
    float h = size.height;
    float cellOffset = (y - h) + 55;
    NSLog(@"%f", cellOffset);
    CurrentArtistHeader *header = (CurrentArtistHeader *)[self.collectionView viewWithTag:50];
    if (cellOffset > 0 && header.frame.size.height < stickyH) {
        
        if (header.frame.origin.y < scrollBoundY) {
            header.frame = CGRectMake(header.frame.origin.x,
                                      header.frame.origin.y - cellOffset,
                                      header.frame.size.width,
                                      header.frame.size.height + cellOffset);
        }
        
        else    header.frame = CGRectMake(header.frame.origin.x,
                                          header.frame.origin.y - cellOffset,
                                          header.frame.size.width,
                                          header.frame.size.height);
        
    }
}


Again, this wouldn't even be a problem if I could somehow update the view programmatically the same way that scrolling instantly fixes the problem. Theres no way (at the moment) to fix for when the user removes a cell twice without scrolling in between removals. The headers frame will get misplaced since the bounds are not updated after reloading the collection view's data.

**Comment by afriedman94** [comment]
Okay, so a large problem was with how I was removing cells from the collection view. This is how I am doing it now. 

    -(void)removeFirstItemFromCollectionView
    {
           [self.collectionView performBatchUpdates:^{
           //delete item from hostQueue
           [self.hostQueue removeObjectAtIndex:0];
           // Now delete the items from the collection view.
           [self.collectionView deleteItemsAtIndexPaths:@[[NSIndexPath indexPathForItem:0 inSection:0]]];
       } completion:nil];
   }

Now, Upon removing a cell, the header will stay pinned to the animation of the deletion of the first cell. So it will move down then pop back to its normal position. Perhaps I need to customize the animation?

**Comment by jamztang** [comment]
Yes you've got to use the performBatchUpdates API from UICollectionView. However the sticky header issue I haven't find a way to solve.

**Comment by afriedman94** [comment]
This code pretty much completely covers up the problem for me for now. Obviously not how it should be done but at the moment its working exactly how I want it. 

    -(void)removeFirstItemFromCollectionView
     {
        [UIView animateWithDuration:0 animations:^{
            [self.collectionView performBatchUpdates:^{
                [self headerFrameForCellOffset];
               //delete item from hostQueue
                [self.hostQueue removeObjectAtIndex:0];
                // Now delete the items from the collection view.
                 NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:0];
               NSArray *indexPaths = @[indexPath];
               [self.collectionView deleteItemsAtIndexPaths:indexPaths];
               NSLog(@"%i", [self.hostQueue count]);
           } completion:nil];
       }];
    }

     -(void)headerFrameForCellOffset
    {
        float stickyH = self.stickyHeaderFlowLayout.parallaxHeaderReferenceSize.height;
        float scrollBoundY = self.stickyHeaderFlowLayout.parallaxHeaderReferenceSize.height -           self.stickyHeaderFlowLayout.parallaxHeaderMinimumReferenceSize.height;
         CGPoint offset = self.collectionView.contentOffset;
         CGRect bounds = self.collectionView.bounds;
         CGSize size = self.collectionView.contentSize;
        UIEdgeInsets inset = self.collectionView.contentInset;
        float y = offset.y + bounds.size.height - inset.bottom;
       float h = size.height;
        float cellOffset = (y - h) + 55;
        CurrentArtistHeader *header = (CurrentArtistHeader *)[self.collectionView viewWithTag:50];
        if (cellOffset > 0 && header.frame.size.height < stickyH) {
        
            if (header.frame.origin.y < scrollBoundY) {
                header.frame = CGRectMake(header.frame.origin.x,
                                         header.frame.origin.y - cellOffset,
                                      header.frame.size.width,
                                      header.frame.size.height + cellOffset);
           }
        
          else    header.frame = CGRectMake(header.frame.origin.x,
                                          header.frame.origin.y - cellOffset,
                                          header.frame.size.width,
                                          header.frame.size.height);
        }

    }

**Comment by jamztang** [comment]
Looks like some tedious hack. It'd be great if you can help modify the Spotify example and demonstrate the issue, so we can track down the exact bug

**Comment by jamztang** [comment]
as of 0.2.8 we should have squashed some animation issues as well. closing this off for now.
