### ISSUE TITLE
Unable to compile CSStickyHeaderFlowLayoutAttributes (v0.2.4)

### ISSUE THREAD

**Issue by pattrawoots** [jamztang/CSStickyHeaderFlowLayout#57]
![screen shot 2558-03-20 at 9 53 28 pm](https://cloud.githubusercontent.com/assets/34550/6753855/9b3cfdec-cf4b-11e4-875d-f0a43926c436.png)

After upgrading CSStickyHeaderFlowLayout to v0.2.4, I got a compiler error. CSStickyHeaderFlowLayoutAttributes.m cannot be compiled.

**Comment by jamztang** [comment]
Just tested on Xcode 6.2 and looking fine to me, which Xcode version you're using?

**Comment by pattrawoots** [comment]
I'm using Xcode 6.2 (6C131e).

![screen shot 2558-03-22 at 11 10 08 pm](https://cloud.githubusercontent.com/assets/34550/6770109/a3332208-d0e8-11e4-8388-e3e2d4d877eb.png)

If I delete the copyWithZone: method, the app can be built successfully.

**Comment by jamztang** [comment]
may you try checkout a fresh copy of the proj and try again?

**Comment by pattrawoots** [comment]
aha, I tried creating a new project and added CSStickerHeaderFlowLayout to the project. I looks fine!

However, I still have no idea how to fix my current project. It was working well before upgraded to 0.2.4.

More screenshot is attached.
![screen shot 2558-03-22 at 11 20 35 pm](https://cloud.githubusercontent.com/assets/34550/6770162/e1eeda3a-d0ea-11e4-8473-57820aa78417.png)

**Comment by jamztang** [comment]
Maybe your old project isn't arc enabled?

**Comment by pattrawoots** [comment]
I just found that my "C Language Dialect" is set to C99 not GNU99, and that causes the compiler errors. After changing to GNU99, everything is good.

**Comment by jamztang** [comment]
Glad to know, where do you toggle that settings?

**Comment by pattrawoots** [comment]
It is under Apple LLVM 6.1 - Language section.

![screen shot 2558-04-30 at 12 09 41 pm](https://cloud.githubusercontent.com/assets/34550/7406716/01e5750a-ef32-11e4-9084-115dfbfc456c.png)

**Comment by jamztang** [comment]
ahhh i c, great info for others as well! I'll close this thread for now, thanks!
