### ISSUE TITLE
How can I fill Sticky  header to Status bar?

### ISSUE THREAD

**Issue by truonguit2010** [jamztang/CSStickyHeaderFlowLayout#58]
Hi,
I add Sticky header to my view controller. And I hide navigation bar. But Stickyheader don't fill status bar. Please, give me a hand.
![screen shot 2015-04-02 at 12 08 48 am](https://cloud.githubusercontent.com/assets/4622117/6946770/d76c7b46-d8cc-11e4-9437-ca304d638ada.png)

**Comment by jamztang** [comment]
What you can do it set your header's subview inset to -20 to accommodate the status bar height. Make sure your header has `clipToBounds` set to `NO` as well

**Comment by TanguyAladenise** [comment]
Hello
Do we have a solution for this?
@jamztang your solution is not working because if you have a section sticky then its hidden by header.
Am I missing something?

**Comment by TanguyAladenise** [comment]
Found a quick fix while writing my comment.
Setting top content insets of collectionView to -20 is solving the issue. 
Is this due to a collectionView default behaviour?

**Comment by zeeshankhan** [comment]
I tried [this way] (http://stackoverflow.com/a/14336079), but it didn't work for me.
@jamztang what do you mean by 'header's subview inset'? How could I fill the status bar with header?
@truonguit2010 did you get the status bar fix?

**Comment by jamztang** [comment]
set the backgroundView of your header be {0, -20, header.size.width, header.size.height+20}

And make sure header.clipInBounds = false

**Comment by zeeshankhan** [comment]
@jamztang `header.clipsToBounds = false;` works but when we scroll up header doesn't shrink. It is coming over the list.

**Comment by jamztang** [comment]
For shrink you mean didn't clip? Then you may have to create a wrapper around the background view and all its content and set that enable clips to bounds instead.

This sounds stupid but I am not sure if there's a better solution for us to work around collection view behaviour when the nav bar is disabled

**Comment by jamztang** [comment]
Make sure you have setup auto layout constraints on your wrapper as well

**Comment by zeeshankhan** [comment]
@jamztang Thanks for the help, It worked perfectly. I was missing something. And this component awesome, thanks for sharing! Cheers :+1: :)

**Comment by jamztang** [comment]
cool, I'll close it for now! cheers!
