### ISSUE TITLE
Setting contentInset causes header image to "jump" from bottom to top

### ISSUE THREAD

**Issue by shivateja** [jamztang/CSStickyHeaderFlowLayout#59]
I'm building an application which has a UITextField outside the collection view. I'm trying to animate setting the bottom inset to cover up the space occupied by the keyboard. Setting contentInset in the animation block causes the header image jump bottom to top sometimes.

Here's the video demonstrating the problem.
http://cl.ly/0w3x1X3f0p0v

The following is the code used for setting the insets. The UITextField is independent of the Collection View and has a bottom constraint with the bottom layout guide.

```swift
    func keyboardWillShow(notification: NSNotification){
        let info: NSDictionary = notification.userInfo!
        let keyboardFrame = (info[UIKeyboardFrameEndUserInfoKey] as NSValue).CGRectValue()
        
        // Take the comment box up
        bottomHeightConstraint.constant = keyboardFrame.height
        self.view.setNeedsUpdateConstraints()
        
        UIView.animateWithDuration(1, delay: 0, options: UIViewAnimationOptions.BeginFromCurrentState, animations: { () -> Void in
            self.view.layoutIfNeeded()
            // Inset from bottom equal to the height of keyboard
            self.collectionView.contentInset = UIEdgeInsetsMake(0, 0, keyboardFrame.height, 0)
            }, completion: nil)
    }
    
    func keyboardWillHide(notification: NSNotification){
        // Bring the comment box down
        bottomHeightConstraint.constant = 0
        self.view.setNeedsUpdateConstraints()

        UIView.animateWithDuration(1, delay: 0, options: UIViewAnimationOptions.BeginFromCurrentState, animations: { () -> Void in
            self.view.layoutIfNeeded()
            self.collectionView.contentInset = UIEdgeInsetsZero
            }, completion: nil)
    }
```

I'm not aware of UICollectionView internals and the layouts but I'm guessing the problem is in the layout's header rendering code. Is there any solution/better way to solve this? Thanks in advance!

**Comment by brunobasas** [comment]
Same problem here

**Comment by DanielDaverio** [comment]
Ok, the problem could be temporally fixed to if we omit the initialLayoutAttributesForAppearingSupplementaryElementOfKind, that was causing a wrong frame on layoutAttributesForElementsInRect to work with the CSStickyHeaderFlowLayoutAttributes.

**Comment by jamztang** [comment]
yes thanks, I think 0.2.8 should have fixed the issue, please feel free to reopen if the problem continues
