### ISSUE TITLE
Layout assertion failure

### ISSUE THREAD

**Issue by jessesquires** [jamztang/CSStickyHeaderFlowLayout#6]
Project setup as specified in README.

```
 *** Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the view returned from -collectionView:viewForSupplementaryElementOfKind:atIndexPath (CSStickyHeaderParallexHeader,<NSIndexPath: 0x15eba8e0> {length = 2, path = 0 - 0}) was not retrieved by calling -dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath: or is nil ((null))'
*** First throw call stack:
```

**Comment by Chren** [comment]
Problem still continues.
I want to use sectionheader for some specific section, not all of sections,
So I return CGSizeZero in referenceSizeForHeaderInSection for sections don't need header,
and return nil in viewForSupplementaryElementOfKind for section don't need header,
and it crashes with the log jessesquires mentioned.

**Comment by jamztang** [comment]
You probably shouldn't return nil but returning an instance of UICollectionReusableView() as a workaround.

If you feel like experimental, I just merged a pull request might help in your case, please use the latest commit or update your Podfile to use it. Let me know if things works work you :)

```
pod 'CSStickyHeaderFlowLayout', :head
```
