### ISSUE TITLE
Support device rotation

### ISSUE THREAD

**Issue by netwire88** [jamztang/CSStickyHeaderFlowLayout#61]
@jamztang This project is awesome! Saved me so much time. Thank you! One quick question, I don't think the demo project supports device rotation, see screenshot below. How can the header support rotation?

![image](https://cloud.githubusercontent.com/assets/1209073/7075502/8c7b13fe-ded0-11e4-8613-616cc0d34686.png)

**Comment by jamztang** [comment]
So this is more like a generic UICollectionView question. We have an answer in #14 :) And of course you may also needed to adjust your constraints, cheers!
