### ISSUE TITLE
How to create "Spotify" example programmatically?

### ISSUE THREAD

**Issue by chrise86** [jamztang/CSStickyHeaderFlowLayout#63]
I'm having problems creating the "Spotify" example programmatically. The header does not scroll away and I can't get the button (a UISegmentedControl, in my case) to stick at the top.

Could you please post an example of how to create the header and set it up programmatically, without IB and NIBs?

**Comment by jamztang** [comment]
I'm afraid I'm not the best person to put up examples on auto layout constraints programmatically, nor the intention of this project to do that, but I can explain a bit.

Think of **CSStickyHeaderParallaxHeader** as the UITableView's `tableHeaderView` here, but the main difference is that the `bounds` of the header will automatically "stretches" according to the scroll offset. this is what all the library does for the header.

So when you add <your subview> with all four edges set to 0 to the header, it "stretches" as well. If you wanted it to "push up", you have to either config these:

1. set the `minimumReferenceSize` property of the layout, so when the scroll offset start getting less than it, it stops updating the size.

OR:

2. Set an explicit height to <your subview>, and remove or lower the priority of the top constraint. This would results that when the scroll offset start getting smaller, it "breaks" the top constraint.

You're required to set up correct constraints yourself to achieve the parallax effect.

Try look closer into the Spotify header nib file, we're making use of a number of auto layout tricks to achieve certain effects for each of the layer in the header (You should translate the constraints to code manually if you're required to use code). Once you understand you will notice you can actually can do even more than just parallax.

Hopes this helps.

**Comment by chrise86** [comment]
Thanks James, I managed to solve it - had to adjust some constraints, basically swapping top for bottom constraints.

**Comment by jamztang** [comment]
glad to help, Chris!
