### ISSUE TITLE
swift applyLayoutAttributes inconsistent

### ISSUE THREAD

**Issue by osmantuna** [jamztang/CSStickyHeaderFlowLayout#64]
The sample you provided using "CSStickyHeaderFlowLayoutAttributes" as parameter type but when i used in swift it came with  "UICollectionViewLayoutAttributes" base class

your sample
```obj-c
- (void)applyLayoutAttributes:(CSStickyHeaderFlowLayoutAttributes *)layoutAttributes {
```
swift
```swift
override func applyLayoutAttributes(layoutAttributes: UICollectionViewLayoutAttributes!) {
```
i created another variable and used this way
```swift
let attr = layoutAttributes as! CSStickyHeaderFlowLayoutAttributes
```

**Comment by jamztang** [comment]
so does it work when you cast it?

**Comment by osmantuna** [comment]
yes, it did

**Comment by jamztang** [comment]
what was the issue?

**Comment by osmantuna** [comment]
you have a variable called "progressiveness" on CSStickyHeaderFlowLayoutAttributes class and it does not exist in "UICollectionViewLayoutAttributes" class. so when i try this code, "progressiveness" variable gives error which is not found 

```obj-c
if (layoutAttributes.progressiveness <= 0.58) {
        self.titleLabel.alpha = 1;
    } else {
        self.titleLabel.alpha = 0;
    }
```

**Comment by jamztang** [comment]
Do you mean it's an issue that you have to cast it `CSStickyHeaderFlowLayoutAttributes` to use those properties?

**Comment by lalmachado** [comment]
yes, it is, same problem here

**Comment by jamztang** [comment]
I looked into the Swift header of UICollectionView, I think Apple didn't optimise it in Swift way. Since we couldn't override our method in Swift like objective-C does, manually casting is probably required in this scanario. I am not sure there's a better way to solve this from our side.

**Comment by jamztang** [comment]
To write this off, casting should be the only way to properly do it as it's how the SDK designed.

```
if let attr = layoutAttributes as? CSStickyHeaderFlowLayoutAttributes {
   // do something
}
```
