### ISSUE TITLE
A crash when parallaxHeaderReferenceSize is changed

### ISSUE THREAD

**Issue by kamarshad** [jamztang/CSStickyHeaderFlowLayout#65]
Changing the the ParallaxHeaderCell Size crashing with below exception logs.
To reproduce just increase the height of CSParallaxHeader and also set below value(or whatever value more than to 200)

layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 400);

Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. Try this:
 (1) look at each constraint and try to figure out which you don't expect; 
 (2) find the code that added the unwanted constraint or constraints and fix it.
 
(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the    documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 

"NSAutoresizingMaskLayoutConstraint:0x1587f4a0 h=-&- v=-&- UIView:0x14506fb0.height 
== UICollectionViewCell:0x145f4e70.height - 0.5"
 "NSLayoutConstraint:0x15878fc0 'UIView-Encapsulated-Layout-Height' V:  [UICollectionViewCell:0x145f4e70(0)]"

Will attempt to recover by breaking constraint 
NSLayoutConstraint:0x15878fc0 'UIView-Encapsulated-Layout-Height' V [UICollectionViewCell:0x145f4e70(0)]

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

Any idea how can I resolve it

**Comment by jamztang** [comment]
So just make sure you understand, it's not actually crashing but throwing an auto layout exception. It indicates something wrong with the constraint setup.

However, I'm using the sample project and couldn't reproduce the issue.
I'm changing `-[CSParallaxHeaderViewController reloadButtonDidPress:]` implementation.

```objective-c
- (IBAction)reloadButtonDidPress:(id)sender {
    CSStickyHeaderFlowLayout *layout = self.collectionViewLayout;
    layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 400);
}
```

Can you provide an example on your issue?

**Comment by kamarshad** [comment]
@jamztang  Yes its giving above exception and crashing also with above auto-layout warning 

As of now I do not have separate example but you can reproduce crash by doing following changes in your existing demo(CSParallaxHeaderViewController and its corresponding parallaxCell),

A.    layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 200);
B.ParallaxCell should be same height of parallaxHeaderReferenceSize i.e 200 and ImageView placed in Cell height should be 500  with three constraint 1.AlighCenterConstraint Y 2.TrailingAlignmentConstraint 3.leadingAlignment  4.heightConstraint (500)

C.App should be running on iOS 7.X
D.You should scroll till parallaxCell goes to offscreen

**Comment by kamarshad** [comment]
@jamztang  I got the actual reason behind this issue self.automaticallyAdjustsScrollViewInsets is set to default YES (which allows the view controller to adjust its scroll view insets in response to the screen areas consumed by the status bar, navigation bar, and toolbar or tab bar.Set to NO if you want to manage scroll view inset adjustments yourself)

Once I set the  self.automaticallyAdjustsScrollViewInsets  = NO;
Neither I am getting auto-layout warning nor application getting crashed 

Thanks for your support @jamztang  :+1:

**Comment by kamarshad** [comment]
@jamztang  I got the actual reason behind this issue self.automaticallyAdjustsScrollViewInsets is set to default YES (which allows the view controller to adjust its scroll view insets in response to the screen areas consumed by the status bar, navigation bar, and toolbar or tab bar.Set to NO if you want to manage scroll view inset adjustments yourself)

Once I set the  self.automaticallyAdjustsScrollViewInsets  = NO;
Neither I am getting auto-layout warning nor application getting crashed 

Thanks for your support @jamztang  :+1:

**Comment by jamztang** [comment]
wow, never thought `automaticallyAdjustsScrollViewInsets` has anything to do with auto layout. Glad to know you've fixed the issue! Cheers.
