### ISSUE TITLE
ld: library not found for -lPods

### ISSUE THREAD

**Issue by liuxuan30** [jamztang/CSStickyHeaderFlowLayout#66]
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It should not include any third party stuff in compiler if you don't have the code.

**Comment by jamztang** [comment]
Do you open the project with .xcworkspace?

**Comment by mitesh1301** [comment]
hi jamztang,

i am also facing same kind of error.I just opened my project wit workspace.
