### ISSUE TITLE
How to prevent CollectionView to remove headers not in bounds.

### ISSUE THREAD

**Issue by kamarshad** [jamztang/CSStickyHeaderFlowLayout#67]
I am using your great library and I want to prevent collection view to remove header view not in bounds.
Scrolling collection view  up/down and if header view goes offscreen(not in bound) should not be removed.

Can you @jamztang please help me?

**Comment by jamztang** [comment]
You'll want to update the method `-[CSStickyHeaderFlowLayout layoutAttributesForElementsInRect:]`, at the end before returning the **allItems**, enumerate over it and add the missing supplementary view's layout attributes.

**Comment by kamarshad** [comment]
@jamztang  Thanks for your prompt reply.
I forgot to mention that header view is Parallax Header and the same code already written in your library(CSStickyHeaderFlowLayout class)inside the layoutAttributesForElementsInRect, enumerating all attributes item method inside the below condition
if (visibleParallexHeader && ! CGSizeEqualToSize(CGSizeZero, self.parallaxHeaderReferenceSize))

**Comment by kamarshad** [comment]
@jamztang Got the solution but wanted through pod.
Well reason behind this was a single line written inside the class `CSStickyHeaderFlowLayout.m`

In method `layoutAttributesForElementsInRect`  
             `CGFloat height = MAX(0, -y + maxY);`
I don't logic behind keeping 0 in above statement(might be you won't let negative).when I put any positive integer value like 50 it working fine.

I have tested on each device(4, 4.7 and 5 inches) working fine.
If possible,Can you please make this change.

**Comment by jamztang** [comment]
This will change the existing behaviour for all other people using this library. Try make it 150 and check the demo "Grow" and "AlwaysOnTop" tab, definitely what others wanted.

I am not quite sure what you wanted to achieve, I wonder if the existing `parallaxHeaderMinimumReferenceSize` is the answer for you, try set it a positive number.

You can also create your own pod for the specific change of your own, just fork the project it under your profile, and you can specify the repo by changing this line in your podfile.

```
pod 'CSStickyHeaderFlowLayout', :git => 'https://github.com/kamarshad/CSStickyHeaderFlowLayout.git'
```

**Comment by jamztang** [comment]
Closing this for now as of specific changes
