### ISSUE TITLE
Section header go behind cell when insert via performBatchUpdates

### ISSUE THREAD

**Issue by sarunw** [jamztang/CSStickyHeaderFlowLayout#68]
If I use insert and performBatchUpdates instead of reloadData I always get the problem where header hidden behind cells
![output](https://cloud.githubusercontent.com/assets/795368/7251208/5e5b1dca-e853-11e4-970a-aff51400c07f.gif)

I also got example project https://dl.dropboxusercontent.com/u/2271974/CSStickyHeaderFlowLayout.zip, the part I change is this chunk of code

```
- (void)add:(id)sender
{

    [self.collectionView performBatchUpdates:^{
        NSArray *new = @[
                         @{@"Twitter":@"http://twitter.com"},
                         @{@"Facebook":@"http://facebook.com"},
                         @{@"Tumblr":@"http://tumblr.com"},
                         @{@"Pinterest":@"http://pinterest.com"},
                         @{@"Instagram":@"http://instagram.com"},
                         @{@"Github":@"http://github.com"},
                         @{@"Twitter":@"http://twitter.com"},
                         @{@"Facebook":@"http://facebook.com"},
                         @{@"Tumblr":@"http://tumblr.com"},
                         @{@"Pinterest":@"http://pinterest.com"},
                         @{@"Instagram":@"http://instagram.com"},
                         @{@"Github":@"http://github.com"},
                         ];
            self.sections = [self.sections arrayByAddingObjectsFromArray:new];
        
        NSMutableIndexSet *set = [NSMutableIndexSet indexSet];
        NSMutableArray *indexPaths = [NSMutableArray array];
        
        int startIndex = 0;
    [new enumerateObjectsUsingBlock:^(NSDictionary *item, NSUInteger idx, BOOL *stop) {
        NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:startIndex + idx];
        [indexPaths addObject:indexPath];
        
        [set addIndex:startIndex + idx];
        
    }];
        
        [self.collectionView insertSections:set];
        [self.collectionView insertItemsAtIndexPaths:indexPaths];
    } completion:nil];
}
```

**Comment by jamztang** [comment]
Seems to be something to do with the zIndex, I'll have to get time to take a look

**Comment by aryaxt** [comment]
I'm noticing the same issue

**Comment by matrpedreira** [comment]
I'm having this problem when changing the size of the the array that is being used on the collection data source and then calling reloadData.

**Comment by matrpedreira** [comment]
Thx for the update. Your API is awesome and your support to it is impressive. We were about to send to apple store and discovered this bug. Once we launch there we are going to put our app on your wiki and you license is definitively on the apple easy to find to support your work. Great job.

**Comment by jamztang** [comment]
Thanks @matrpedreira, it happens that I finally got time to resolve this issue, all credits should goes to @sarunw for providing a great sample test case for us to get right started.

**Comment by aryaxt** [comment]
@jamztang I think this fix cause another issue where now the scroll indicator goes behind the cells

**Comment by jamztang** [comment]
```
pod 'CSStickyHeaderFlowLayout', :branch => 'master'
```

While it's not pushed to cocoapods yet, try this or use `0.2.5`

**Comment by jamztang** [comment]
Guys, 0.2.7 is available on cocoa pods!

**Comment by aryaxt** [comment]
Thanks, works well now

**Comment by ckakei** [comment]
This change make the collection item from storyboard cannot show
