### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by troypayne** [jamztang/CSStickyHeaderFlowLayout#70]
Hi.

I'm trying to figure out (from a high level) how this class works so I can try and fix a bug i'm having where my sticky header is a UIScrollView with a bunch of UIImageView's, but when i pull down after scrolling, it always shows the stretching image of the initial UIImageView in the UIScrollView...

**Comment by jamztang** [comment]
The header might be reused (as it's a supplementary view), try set the page to an instant variable and restore it in -[UICollectionViewDataSource collectionView:viewForSupplementaryElementOfKind:atIndexPath:]

**Comment by troypayne** [comment]
I got this working without doing anything extra. I just properly setup auto layout with a UIScrollView and things just worked as expected
