### ISSUE TITLE
Stretch threshold?

### ISSUE THREAD

**Issue by troypayne** [jamztang/CSStickyHeaderFlowLayout#71]
I've noticed that for some of my smaller images, it stops stretching and instead breaks and shows the bg. Is there a way to prevent this or set the threshold when and when not to break the stretching?

**Comment by jamztang** [comment]
would you describe a bit more or even better to provide a sample project?

**Comment by troypayne** [comment]
Sure, but i'm having a bigger problem now. A performance issue. CPU jumps to 86% because of this library after doing a Time Profiling on it. I may have a unique use case as I don't have a single image in my stretchy header, as I have a UIScrollView filled with about 10 images... it starts to get noticeably crappy after 5 or more images are added to it.

I'm not sure where to begin trying to figure out what could be causing this, do you have any ideas?

**Comment by jamztang** [comment]
Maybe you should really try to use another collection view instead of a scroll view for your header because 10 images in memory is very expensive depending on the resolution, and cell reuse mechanism in collection view is designed to load just enough cells on screen instead of all at once.

**Comment by troypayne** [comment]
@jamztang So I'm trying to use a UITableView instead of a UIScrollView, that i'll simply transform to make scroll horizontally, and enable pagination... but before doing that I want to make sure that I can actually stretch the contents.

I've tried to do the following:
https://gist.github.com/anonymous/cdc30d31023d1c125065

but no luck. Any ideas?

**Comment by jamztang** [comment]
Sorry I am on my phone now and couldn't find time for setting up a sample project right now, but here's some pointers.



Seems you want to set constraints to the cell to match the size of the header, but cells are actually managed by tableview you probably not able to control size of cells using constraints. The proper way to change the size is through -[



UITableView setRowHeight:] or use its delegate method. And the proper time to update the cell size is when the bounds changes of the table view, you can either KVO or subclass UITableView and override setBounds:






That's said, i am not a fan of transforming table view for horizontal scroll. My suggestion would be using collection view and just use horizontal mode, setup proper constraints like how you'd do for table view, else are much similar to above




Hopes that helps

James









—

**Comment by troypayne** [comment]
@jamztang got it working, thanks!!!!!

**Comment by jamztang** [comment]
awesome!

**Comment by troypayne** [comment]
Sorry @jamztang i spoke too soon! ha, I created a sample project that demonstrates the problem. I just emailed you the file...

**Comment by jamztang** [comment]
As chatted in email, should have fixed?
