### ISSUE TITLE
Header not going all the way to the top

### ISSUE THREAD

**Issue by danglade** [jamztang/CSStickyHeaderFlowLayout#72]
Hello,

Replicating the same example provided, I'm having this issue where the header does not go all the way to the top.

See image

![image](https://cloud.githubusercontent.com/assets/6461587/7420736/f11d2e28-ef4c-11e4-8082-d17edd9ebc64.png)

**Comment by jamztang** [comment]
If you have a navigationController, you will want to set the imageviews origin.y or topConstraint to -20

**Comment by jamztang** [comment]
Please refer to #58
