### ISSUE TITLE
Header not sticking properly to the top with more then one cell on the section.

### ISSUE THREAD

**Issue by matrpedreira** [jamztang/CSStickyHeaderFlowLayout#74]
![test](https://cloud.githubusercontent.com/assets/2981211/7667732/b920daf4-fbc9-11e4-88d0-9621d0d688c0.gif)

Each section has a header and two items with variable sizes.
The header has a fixed size of the x= width of the screen and y = 48
The image cell has the size x =  width of the screen and y = width of the screen or less
And the text cell has a size x =  width of the screen and y bigger than 112.

For some reason when first scrolling the section header is losing his place and then going back, but after I scrolled through at least one time this doesn't occur anymore.

Could this be a problem on your end or am I doing something wrong.

Great project and I hope this is on my end so that this is not a bug for more people.

**Comment by matrpedreira** [comment]
I discovered that the problem was on my end, when loading the image from the database I was reloading the cell to change the size for the image however that was creating a bug in the app. I fixed that by using in swift:
collectionView.collectionViewLayout.invalidateLayout()
which makes the collection view re-calculate the size for the sections
Great api.

**Comment by jamztang** [comment]
thanks for the info Matheus! Great job and let me know when your app releases, we can add it to the [wiki page](https://github.com/jamztang/CSStickyHeaderFlowLayout/wiki) if you like :D
