### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by hugocroch** [jamztang/CSStickyHeaderFlowLayout#75]
Hi, is it possible to use the CSStickyHeaderFlowLayout in horizontal scroll or it is not supported for the moment?

**Comment by jamztang** [comment]
sorry it's not supported at the moment

**Comment by hugocroch** [comment]
I finally made a version of CSStickyHeaderFlowLayout for horizontal scroll but thanks for the information!

**Comment by bhavinpankanis** [comment]
@hugocroch Could you please share the approach which you have used. I have a similar requirement
