### ISSUE TITLE
always reloading datasource when using another library in parallax header

### ISSUE THREAD

**Issue by xeravim** [jamztang/CSStickyHeaderFlowLayout#76]
so I am using KIImagePager for reloading the imageview inside the parallax header cell:

[cell.imagePager setDelegate:self];
[cell.imagePager setDataSource:self];
[cell.imagePager setSlideshowTimeInterval:3.0f];
[cell.imagePager setImageCounterDisabled:YES];

#dataSource
- (NSArray*)arrayWithImages:(KIImagePager *)pager{
    index++;
    NSLog(@"index:%d",index);
    return self.pictures;
}

so the arraywithImages always called when scrolling up and down, how to initialize the CSStickyHeaderParallaxHeader no to always reloading the data source?

**Comment by jamztang** [comment]
There's no direct way to toggle the reusing behaviour when it goes offscreen right now, but until then you may try to cache your array to make it less expensive instead.

**Comment by jamztang** [comment]
I'll close this for how since it's more like a general cell reuse mechanism issue
