### ISSUE TITLE
How to have a Table-like Layout ?

### ISSUE THREAD

**Issue by qbraksa** [jamztang/CSStickyHeaderFlowLayout#77]
Hi, 

What's the best way to layout the TableView-like part so each cell will have full width and the correct height 

(like in the screenshot below) 

![Screenshot](https://camo.githubusercontent.com/3aab9bc8e28dcde1a0fcd92eeac9d5ccf2507368/687474703a2f2f662e636c2e6c792f6974656d732f30353133307332723058316a3178314e3051336e2f73706f746966792d34382d31362d68616c662e676966)

**Comment by jamztang** [comment]
make sure you're always returning the width of your collection view in the delegate

```
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSizeMake(collectionView.frame.size.width, <# height #>)
    } 
```
