### ISSUE TITLE
Using collectionViewLayout property of UICollectionView

### ISSUE THREAD

**Issue by sumitjain7** [jamztang/CSStickyHeaderFlowLayout#79]
I am not using UICOllectionViewController. I added a UICollectionView in a UIViewController.

I want to use this
var layout:CSStickyHeaderFlowLayout = self.collectionView.collectionViewLayout
layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.width, 50);
layout.parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.width, 50);

I am receiving compilation error in using collectionViewLayout property.
error: Could not find member 'collectionViewLayout'

**Comment by jamztang** [comment]
You should do this:

```
if let layout = self.collectionView.collectionViewLayout as? CSStickyHeaderFlowLayout {
    // do something with your layout
}
```
