### ISSUE TITLE
Unable to run 'pod install' on example project

### ISSUE THREAD

**Issue by rtimpone** [jamztang/CSStickyHeaderFlowLayout#83]
I cloned the repo and ran 'pod install' from the Project directory, but I'm getting the following error from cocoapods:

    [!] Unable to satisfy the following requirements:

    - `CSStickyHeaderFlowLayout (from `../CSStickyHeaderFlowLayout.podspec`)` required by `Podfile`
    - `CSStickyHeaderFlowLayout (= 0.2)` required by `Podfile.lock`

I'm using cocoapods version 0.37.2. It looks like the problem is that cocoapods is trying to treat '../CSStickyHeaderFlowLayout.podspec' as a directory rather than a podspec file. I found two possible fixes for this:

1.) Change :path to :podspec in the Podfile, forcing cocoapods to realize the path leads to a podspec file rather than a directory:

    pod "CSStickyHeaderFlowLayout", :podspec => "../CSStickyHeaderFlowLayout.podspec"

2.) Change the path in the Podfile to "../", leading cocoapods to the directory the podspec is located in rather than the podspec file itself:

    pod "CSStickyHeaderFlowLayout", :path => "../"

The second option seems a little better because the :path Podfile directive is much more commonly used than the :podspec one, and it has more documentation backing it up.

**Comment by jamztang** [comment]
Fix merged so closing this off

**Comment by thbaja** [comment]
It seems the problem hasn't been fixed:
```
➜  Project git:(master) ✗ pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `CSStickyHeaderFlowLayout` from `../`
[!] Unable to satisfy the following requirements:

- `CSStickyHeaderFlowLayout (from `../`)` required by `Podfile`
- `CSStickyHeaderFlowLayout (= 0.2.7)` required by `Podfile.lock`
```

**Comment by rtimpone** [comment]
Podfile.lock is probably out of sync with the Podfile since version 0.2.8 of CSStickyHeaderFlowLayout is now available. Running "pod update" instead of "pod install" should allow you to fetch the podspec as normal.

**Comment by jamztang** [comment]
I thought if committed the Podfile.lock in the sample project users will not need to run `pod install` to run the sample?

**Comment by thbaja** [comment]
`pod install` works :+1:
