### ISSUE TITLE
strange animation when increasing contentInset

### ISSUE THREAD

**Issue by kyfxbl** [jamztang/CSStickyHeaderFlowLayout#85]
hi james,

i use CSStickyHeaderFlowLayout for parallax CollectionView, and i add a pulling-to-refresh component on this UICollectionView. and after pulling, there is a strange animation. for clear shown, i set the animation duration to 3 seconds. 

[stackoverflow](http://stackoverflow.com/questions/31470722/strange-animation-with-csstickyheaderflowlayout-and-mjrefresh/31478319?noredirect=1#comment50943846_31478319)

and i setup a sample project, and email to you, thanks a lot @jamztang

**Comment by jamztang** [comment]
It'd be good if you can create an opensource project on github so everyone comment and help



—

**Comment by kyfxbl** [comment]
ok, do it now

**Comment by kyfxbl** [comment]
sample project repo:

https://github.com/kyfxbl/CollectionViewAnimationProblem

**Comment by jamztang** [comment]
Let me know if that works for you @kyfxbl, then I'll push to CocoaPods

**Comment by kyfxbl** [comment]
@jamztang awesome, now it works fine :)  thanks in advance

by the way, maybe you have noticed that, i use masonry for auto layout within SupplementaryView, otherwise the header couldn't be sticky: the SupplementaryView shrinked, but its subviews remain there. so i want to know, if it's best practice (or only right way) to use auto layout accompany with CSStickyHeaderFlowLayout?

the wrong code, header won't be sticky:
```
UILabel *header1 = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 375, 50)];
header1.backgroundColor = [UIColor yellowColor];
header1.text = @"1111";
        
UILabel *header2 = [[UILabel alloc] initWithFrame:CGRectMake(0, 50, 375, 50)];
header2.backgroundColor = [UIColor blueColor];
header2.text = @"2222";
```

**Comment by jamztang** [comment]
Yes you'll have to setup your autolayout or autoresizing mask for that. The mechanism behind CSStickyParallaxHeader is that the library will handle the origin and height of the header for you, that means the origin is always sticks to the top and adding height to accommodate the visible areas. So if you don't setup how the subviews will "flow" inside the supplementary view, you won't get the desire result. How ever if you do it correctly, the possibilities are endless, like the few different apps I made and showcases in the readme.

One reminder is that It's important to configure the `parallaxHeaderMinimalReferenceSize` as well so it'll "push" away the header at desired point.

There's also another "sticky section header" that the library provides, it's like ordinary section headers in collection view and table views, but it tried to "stick" just below the parallax header.

Hope that explains.

**Comment by kyfxbl** [comment]
got it, thank you very much. so i close the issue, amazing lib!

**Comment by jamztang** [comment]
No problem, glad to help!


—
