### ISSUE TITLE
Using it in swift project and without storyboards

### ISSUE THREAD

**Issue by bbhagat** [jamztang/CSStickyHeaderFlowLayout#86]
Hi, 

I am trying to use the library in a swift project. I am not using storyboards in the application. I took a look at the swift example and implemented it in similar fashion. I also took a look at the obj-c project and make some changes accordingly. But I am not able to achieve the effect where the header would scroll up and the section header of collection view would stick to the top of the view. Below is the link to the video. The example in swift is really basic. Can you please enhance it a bit to show the sticky section header effect. 

https://www.dropbox.com/s/26jph7gmswqdher/ScreenCap.mov?dl=0

PS: This is not an issue. Just looking for some help/pointers. I guess people have been successful after a few attempts to get the required effect in swift.

**Comment by bbhagat** [comment]
@jamztang, can you help? I made a lot of changes but I am still facing the problem. 

Regards,
Bhavik

**Comment by jamztang** [comment]
Seems like you're using CSStickyParallaxHeader instead of section header. As of your description you will need to setup section header instead.

**Comment by bbhagat** [comment]
Hi @jamztang 

**First of all thanks for this amazing OSS and thanks for the reference and suggestion.** I took a  look at the suggestion and example that you added in swift demo project and I dont think it still solves my problem. What I am trying to achieve requires a parallax header along with sticky section header. The parallax header should scroll up and should have a sticky section header. The effect that I am trying to achieve is as per screenshots attached. Below is sample extract from my code. Sorry if my question was a little misleading. I have uploaded a new video on the link below with the current state. 

Problem: The parallax header wont scroll up. Every time I scroll it up, it scrolls down on its own. It does not stay at its position. I tried parallaxHeaderAlwaysOnTop = false and true, but it still brings back the parallax header to its original position. 

My main xib file ABC.xib has only one single collection view which takes up the entire space of the view. 

```
class ABC: UICollectionViewController, UICollectionViewDelegateFlowLayout, CollectionViewRefreshDelegate {
    
    // some code

    var activityFeedItem : [String] = ["AF:: Item 1", "AF:: Item 2", "AF:: Item 3", "AF:: Item 4"]
    var setupFeedItem : [String] = ["S:: Item 1", "S:: Item 2", "S:: Item 3", "S:: Item 4"]
    
    private var layout : CSStickyHeaderFlowLayout? {      
        return self.collectionView?.collectionViewLayout as? CSStickyHeaderFlowLayout
    }
    
    override func viewDidLoad() {        
        super.viewDidLoad()
        self.view.backgroundColor = UIColor.lightGrayColor()
        initCollectionView()
        reloadLayout()
    }
    
    override func willAnimateRotationToInterfaceOrientation(toInterfaceOrientation: UIInterfaceOrientation, duration: NSTimeInterval) {
        reloadLayout()
    }
    
    func initCollectionView() {        
        self.collectionView?.backgroundColor = UIColor.lightGrayColor()
        self.collectionView?.alwaysBounceVertical = true
        self.collectionView?.scrollIndicatorInsets = UIEdgeInsetsMake(0, 0, 0, 0)
        
        self.collectionView?.registerClass(TDCVC.self, forCellWithReuseIdentifier:TDCI)
        
        self.collectionView?.registerNib(UINib(nibName: "TDHV", bundle: nil),
            forSupplementaryViewOfKind: CSStickyHeaderParallaxHeader,
            withReuseIdentifier: TDHI)
        
        self.collectionView?.registerNib(UINib(nibName: "TDSHV", bundle: nil),
            forSupplementaryViewOfKind: UICollectionElementKindSectionHeader,
            withReuseIdentifier:TDSHI)
    }

    func reloadLayout() {
        
        layout?.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 150)
        layout?.parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.size.width, 50)
        layout?.parallaxHeaderAlwaysOnTop = true
        
        // If we want to disable the sticky header effect
        //layout?.disableStickyHeaders = true
    }
```

![687474703a2f2f662e636c2e6c792f6974656d732f3371327533353031336f30793047326f335831762f63617273686172652d33322d31362d68616c662e676966](https://cloud.githubusercontent.com/assets/2133586/8844968/92c97f92-30cf-11e5-8a9b-0d180192622a.gif)
![687474703a2f2f662e636c2e6c792f6974656d732f30353133307332723058316a3178314e3051336e2f73706f746966792d34382d31362d68616c662e676966](https://cloud.githubusercontent.com/assets/2133586/8844969/92cb80bc-30cf-11e5-8e88-812ccaa57a10.gif)

**Comment by jamztang** [comment]
Is there a demo of your current state so you can let us see, I have hard time visualising the issue you described.

**Comment by jamztang** [comment]
ok I saw the link, for some reason it wasn't there before.

The issue you describe about the parallax header is that it reverts itself back to position after you scroll.
That is the normal behaviour of UICollectionView when you don't have enough items to fill up the screen.

**Comment by bbhagat** [comment]
Hi @jamztang ,

Thanks man. I have no clue why and how I missed such a simple and basic thing. Spent two days just debugging this. :( 

Thanks once again for the help. 

- Bhavik

**Comment by jamztang** [comment]
Awesome, glad to help you resolved the issue! If you release your app you can consider putting the link in the wiki page :)
