### ISSUE TITLE
Crashes in iOS 7.1 in viewForSupplementaryElementOfKind method

### ISSUE THREAD

**Issue by davidnelson777** [jamztang/CSStickyHeaderFlowLayout#89]
In the method:
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath

you will get a crash for [kind isEqualToString:UICollectionElementKindSectionHeader] when you try to dequeue a header with method below:

- (id)dequeueReusableSupplementaryViewOfKind:(NSString*)elementKind withReuseIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath*)indexPath;

I went back to version 0.2.3 to avoid the crash, but in the latest versions, (tested in 0.2.5 and 0.2.8) you will get this weird crash with an obscure error in the log.

**Comment by jamztang** [comment]
doesn't sound right to me. any crash logs and sample projects?

**Comment by davidnelson777** [comment]
I forgot to include this: I set some headers to zero size, since I don't want to display the section headers for some sections.
So, the reason this occurs is because the layout sets a size, or estimate size for the header, in iOS 7, CollectionView handles this differently that iOS 8. In iOS 7 it will still call the 
(UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
Even if the header's height is set to 0 in the datasource.
I'm just wondering if you could remove the estimate size in the layout for iOS < 8?

**Comment by rishabhtayal** [comment]
@jamztang I believe it occurs when the ```delegate``` of ```UICollectionView``` is set to our view controller.

**Comment by jamztang** [comment]
It'd be great if we can setup a sample project to reproduce the crash

**Comment by StarWars** [comment]
@davidnelson777 check out the changes in https://github.com/jamztang/CSStickyHeaderFlowLayout/pull/104 
I am sure they will help you.
