### ISSUE TITLE
header scrolls at slightly different speed than collection view 

### ISSUE THREAD

**Issue by Werbelow** [jamztang/CSStickyHeaderFlowLayout#90]
Awesome library! This is something I spent way too long trying to research and make. I have created the below layout, everything works and looks great, until you scroll up quickly, then the header portion (the avatar down to the end of the gray box), scrolls at a slightly different speed than the collection view below it. Kind of creating a bouncing effect. Also if you scroll up or down quick enough, the two separate and you can see through to the background. 

![header-scroll](https://cloud.githubusercontent.com/assets/5963934/8989912/51590568-36ac-11e5-9537-d2be17e36bb5.gif)

Any thoughts on what might be causing it?

Here is a picture showing the background showing through between the header and the Collection View:

![ios simulator screen shot jul 30 2015 2 55 56 pm](https://cloud.githubusercontent.com/assets/5963934/8994892/476012a8-36cb-11e5-8c7e-3ce5b3448a08.png)

Cheers

**Comment by jamztang** [comment]
Are you using csstickyparallaxheader or section header?
Did you try do change the frame during scroll somehow? The second screenshot looks different as of the position of the avatar is in a difference place than the first one. It's good to have an saddle project for us

**Comment by Werbelow** [comment]
I kinda figured out a hacky fix for now, thanks!
