### ISSUE TITLE
ContentInset make sticky header being offset

### ISSUE THREAD

**Issue by TanguyAladenise** [jamztang/CSStickyHeaderFlowLayout#94]
Hi,

First of all thank you for the great repo.
I am currently using it in development. Everything was working correctly until I set a contentInset to one of my collectionView.
With a top contentInset, header are getting sticky at the wrong position.
Any idea where I should look?

Thanks for the help

PS: Bug is easy to reproduce with your locked sample project. I added a contentInset to the collectionView and the same unexpected behavior happens

**Comment by jamztang** [comment]
The library make use of the content inset to determine where it the sticky header should stay, so changing the content insets will change the position of the header sounds right to me

**Comment by TanguyAladenise** [comment]
I guess I was using the contentInset in a way I should not.
Thanks for your reply.
