### ISSUE TITLE
UICollectionViewFlowLayout has cached frame mismatch for index path

### ISSUE THREAD

**Issue by Ewg777** [jamztang/CSStickyHeaderFlowLayout#97]
UICollectionViewFlowLayout has cached frame mismatch for index path.
This is likely occurring because the flow layout subclass CSStickyHeaderFlowLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them. Can you help me?
Xcode 7 beta 6

**Comment by SohailKh** [comment]
same issue

**Comment by jamztang** [comment]
Is that something we can relibly reproduce undone way so we can make sure things are fixed?

**Comment by hengchengfei** [comment]
same issue

**Comment by xindong-liujingfeng** [comment]
Need a new array to undertake the superclass method returns an array, and the array initialization method is the following NSArray (array: [AnyObject], copyItems: Bool) copyItems to true, so as not to appear the above questions, hope useful to you
